name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
      - uses: actions/checkout@v2

      - name: Test
        run:  |
        cd project-react
        npm test
