name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Go to project-react
      #   run: cd project-react

      - name: Test
        run: cd project-react yarn test
